[package]
name = "contract_macros"
version = "0.0.0"
edition = "2018"
autotests = false
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits","full"] }
quote = "0.6"
proc-macro2 = "0.4"